Convert the SOFT to csv for easy visualization
This notebook has the propuse of familiriaze me with the data we have. 
This will clean and place the series matrix and SOFT file to see them on CSV because is the way I like to see them.

In [1]:
import re
import pandas as pd

def parse_soft_file(soft_file_path):
    """Parses a GEO SOFT file and extracts sample metadata."""

    sample_data = []
    current_sample = {}
    reading_sample = False

    with open(soft_file_path, 'r') as infile:
        for line in infile:
            line = line.strip()

            # Detect start of a new sample record
            if line.startswith("^SAMPLE = GSM"):
                if current_sample:
                    sample_data.append(current_sample)
                current_sample = {'GSM': line.split("= ")[1]}  # Initialize with GSM ID
                reading_sample = True
                continue # Skip the rest of the loop and proceed to the next line

            if reading_sample:
                # Extract metadata
                if   "= " in line:
                    parts = line.split("= ")
                    key = parts[0].lstrip("!Sample_")
                    value = parts[1]
                    current_sample[key] = value
                # Handle characteristics annotations

    # Append the last sample
    if current_sample:
        sample_data.append(current_sample)

    return sample_data

def soft_to_dataframe(soft_file_path):
    """Parses SOFT file and returns a pandas DataFrame."""
    data = parse_soft_file(soft_file_path)
    df = pd.DataFrame(data)
    return df

In [38]:
#soft_file = "Data/GSE96058_family.soft" 
soft_file = "/home/karen/Downloads/challenge/GSE81540_family.soft"
df = soft_to_dataframe(soft_file)
df = df.loc[:, (df != df.iloc[0]).any()]
df.to_csv(soft_file, index=True)  # Save as CSV
print(df.head())

          GSM title  geo_accession  submission_date  st_update_date   \
0  GSM2155558     T1     GSM2155558      May 17 2016     Mar 12 2018
1  GSM2155559     T2     GSM2155559      May 17 2016     Mar 12 2018
2  GSM2155560     T3     GSM2155560      May 17 2016     Mar 12 2018
3  GSM2155561     T4     GSM2155561      May 17 2016     Mar 12 2018
4  GSM2155562     T5     GSM2155562      May 17 2016     Mar 12 2018

   characteristics_ch1                                xtract_protocol_ch1   \
0  pam50 subtype: Basal  Poly(A) mRNA is isolated from the total RNA in...
1   pam50 subtype: Her2  Poly(A) mRNA is isolated from the total RNA in...
2   pam50 subtype: LumB  Poly(A) mRNA is isolated from the total RNA in...
3   pam50 subtype: Her2  Poly(A) mRNA is isolated from the total RNA in...
4   pam50 subtype: LumB  Poly(A) mRNA is isolated from the total RNA in...

                                        description   \
0  For pathology key, see pathology_consensus_key...
1  For pathology key, see pathology_consensus_key...
2  For pathology key, see pathology_consensus_key...
3  For pathology key, see pathology_consensus_key...
4  For pathology key, see pathology_consensus_key...

                                    data_processing  tform_id   \
0  Supplementary_files_format_and_content: FPKM g...  GPL11154
1  Supplementary_files_format_and_content: FPKM g...  GPL11154
2  Supplementary_files_format_and_content: FPKM g...  GPL11154
3  Supplementary_files_format_and_content: FPKM g...  GPL11154
4  Supplementary_files_format_and_content: FPKM g...  GPL11154

     instrument_model                                           relation   \
0  Illumina HiSeq 2000  BioSample: https://www.ncbi.nlm.nih.gov/biosam...
1  Illumina HiSeq 2000  BioSample: https://www.ncbi.nlm.nih.gov/biosam...
2  Illumina HiSeq 2000  BioSample: https://www.ncbi.nlm.nih.gov/biosam...
3  Illumina HiSeq 2000  BioSample: https://www.ncbi.nlm.nih.gov/biosam...
4  Illumina HiSeq 2000  BioSample: https://www.ncbi.nlm.nih.gov/biosam...

  series_id
0   GSE81540
1   GSE81540
2   GSE81540
3   GSE81540
4   GSE81540

In [43]:
df.columns

Index(['GSM', 'title ', 'geo_accession ', 'submission_date ',
       'st_update_date ', 'characteristics_ch1 ', 'xtract_protocol_ch1 ',
       'description ', 'data_processing ', 'tform_id ', 'instrument_model ',
       'relation ', 'series_id '],
      dtype='object')

In [44]:
df[df["title "].str.contains("T")]

,GSM,title,geo_accession,submission_date,st_update_date,characteristics_ch1,xtract_protocol_ch1,description,data_processing,tform_id,instrument_model,relation,series_id
0,GSM2155558,T1,GSM2155558,May 17 2016,Mar 12 2018,pam50 subtype: Basal,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
1,GSM2155559,T2,GSM2155559,May 17 2016,Mar 12 2018,pam50 subtype: Her2,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
2,GSM2155560,T3,GSM2155560,May 17 2016,Mar 12 2018,pam50 subtype: LumB,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
3,GSM2155561,T4,GSM2155561,May 17 2016,Mar 12 2018,pam50 subtype: Her2,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
4,GSM2155562,T5,GSM2155562,May 17 2016,Mar 12 2018,pam50 subtype: LumB,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
...,...,...,...,...,...,...,...,...,...,...,...,...,...
400,GSM2155958,T401,GSM2155958,May 17 2016,Mar 12 2018,pam50 subtype: LumA,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
401,GSM2155959,T402,GSM2155959,May 17 2016,Mar 12 2018,pam50 subtype: LumB,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
402,GSM2155960,T403,GSM2155960,May 17 2016,Mar 12 2018,pam50 subtype: Basal,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
403,GSM2155961,T404,GSM2155961,May 17 2016,Mar 12 2018,pam50 subtype: Her2,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540
404,GSM2155962,T405,GSM2155962,May 17 2016,Mar 12 2018,pam50 subtype: LumA,Poly(A) mRNA is isolated from the total RNA in...,"For pathology key, see pathology_consensus_key...",Supplementary_files_format_and_content: FPKM g...,GPL11154,Illumina HiSeq 2000,BioSample: https://www.ncbi.nlm.nih.gov/biosam...,GSE81540

In [3]:
import pandas as pd

def read_series_matrix(file_path):
    """Reads a GEO series matrix file into a pandas DataFrame."""
    with open(file_path, 'r') as f:
        # Determine number of comment lines to skip (starting with "!")
        comment_lines = 0
        for line in f:
            if line.startswith("!"):
                comment_lines += 1
            else:
                break

    # Read data, skipping comment lines
    df = pd.read_csv(file_path, sep='\t', skiprows=comment_lines, index_col=0)
    return df

In [4]:
def clean_series_matrix(df):
    """
    Cleans a GEO series matrix DataFrame by extracting column names
    and values from "name: value" formatted columns.
    """
    column_names=[]
    for col in df.columns:
        # Check if "Sample_characteristics_ch1" is in the column name
        if "!Sample_characteristics_ch1" in col:
            # Extract example value, we will extract the name from the fist row
            example_value = str(df[col].iloc[0])
            print(f"example value: {example_value}")
            name = example_value.split(": ")[0]
            column_names.append(name)
        else:
            column_names.append(col)
    #print(column_names)
    return df

In [29]:
name = "GSE96058-GPL18573_series_matrix.txt"
name= "GSE81540-GPL11154_series_matrix.txt"
matrix_file = f"Data/{name}" 
expression_df = read_series_matrix(matrix_file)
expression_df = expression_df.T
expression_df = expression_df.loc[:, (expression_df != expression_df.iloc[0]).any()]

In [30]:

first_row = expression_df.iloc[0]
column_names=[]
for i, value in enumerate(first_row):
         if  isinstance(value, str) and ": " in value:
            column_names.append(value.split(": ")[0])
         else:
            #If the name does not exist, keept the same as before
            column_names.append(expression_df.columns[i].replace("!",""))
column_names

['Sample_geo_accession',
 'Sample_submission_date',
 'Sample_last_update_date',
 'tissue',
 'er ihc routinestain clinical reading',
 'er ihc routinestain reading 2',
 'er ihc routinestain reading 3',
 'er ihc restain reading 1',
 'er ihc restain reading 2',
 'er ihc restain reading 3',
 'er consensus',
 'pgr ihc routinestain clinical reading',
 'pgr routinestain reading 2',
 'pgr routinestain reading 3',
 'pgr restain reading 1',
 'pgr restain reading 2',
 'pgr restain reading 3',
 'pgr consensus',
 'her2 ihc clinreading',
 'her2 ihc reading 2',
 'her2 ihc reading 3',
 'her2 clinical status',
 'her2 sish reading 1',
 'her2 sish reading 2',
 'her2 sish reading 3',
 'her2 consensus',
 'ki67 reading 1',
 'ki67 reading 2',
 'ki67 reading 3',
 'ki67 consensus',
 'nhg reading 1 tubular',
 'nhg reading 1 pleomorph',
 'nhg reading 1 mitotic',
 'nhg reading 2 tubular',
 'nhg reading 2 pleomorph',
 'nhg reading 2 mitotic',
 'nhg reading 3 tubular',
 'nhg reading 3 pleomorph',
 'nhg reading 3 mitotic',
 'nhg consensus',
 'pam50 subtype',
 'Sample_extract_protocol_ch1',
 'Sample_description',
 'Sample_description',
 'Sample_description',
 'Sample_description',
 'Sample_data_processing',
 'Sample_data_processing',
 'Sample_data_processing',
 'Sample_data_processing',
 'Sample_data_processing',
 'Genome_build',
 'Supplementary_files_format_and_content',
 'Sample_data_processing',
 'Sample_data_processing',
 'BioSample',
 'Sample_relation',
 'series_matrix_table_begin',
 'ID_REF',
 'series_matrix_table_end']

In [31]:
expression_df.columns = column_names

In [32]:
for col in expression_df.columns:
    expression_df[col] = expression_df[col].astype(str).apply(lambda x: x.split(": ", 1)[1] if ": " in x else x)

expression_df

,Sample_geo_accession,Sample_submission_date,Sample_last_update_date,tissue,er ihc routinestain clinical reading,er ihc routinestain reading 2,er ihc routinestain reading 3,er ihc restain reading 1,er ihc restain reading 2,er ihc restain reading 3,...,Sample_data_processing,Genome_build,Supplementary_files_format_and_content,Sample_data_processing,Sample_data_processing,BioSample,Sample_relation,series_matrix_table_begin,ID_REF,series_matrix_table_end
T1,GSM2155558,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,nan,GSM2155558,nan
T2,GSM2155559,May 17 2016,Mar 12 2018,breast tumor,0,0,0,1,0,0,...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,nan,GSM2155559,nan
T3,GSM2155560,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,nan,GSM2155560,nan
T4,GSM2155561,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,nan,GSM2155561,nan
T5,GSM2155562,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,nan,GSM2155562,nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F2912repl,GSM2531475,Mar 09 2017,Mar 12 2018,Q006763.C006741.S002377.l.r.m.c.lib.g.k.a.t,HiSeq 2000,75,19,1to3,NodePositive,1,...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,nan,GSM2531475,nan
F2958repl,GSM2531477,Mar 09 2017,Mar 12 2018,Q005521.C005590.S003572.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,33,12,NA,NA,NA,...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,nan,GSM2531477,nan
F3057repl,GSM2531481,Mar 09 2017,Mar 12 2018,Q005327.C005381.S003761.l2.r.m.c.lib.g.k.a.t,HiSeq 2000,76,91,NodeNegative,NodeNegative,1,...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,nan,GSM2531481,nan
F3085repl,GSM2531483,Mar 09 2017,Mar 12 2018,Q005150.C005183.S003987.l.r.m.c.lib.g.k.a.t,HiSeq 2000,79,10,1to3,NodePositive,1,...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,nan,GSM2531483,nan
F3135repl,GSM2531485,Mar 09 2017,Mar 12 2018,Q004419.C004480.S004739.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,75,18,NodeNegative,NodeNegative,0,...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,nan,GSM2531485,nan

In [45]:
expression_df[expression_df.index.str.contains("T")]

,Sample_geo_accession,Sample_submission_date,Sample_last_update_date,tissue,er ihc routinestain clinical reading,er ihc routinestain reading 2,er ihc routinestain reading 3,er ihc restain reading 1,er ihc restain reading 2,er ihc restain reading 3,...,Sample_data_processing,Sample_data_processing,Sample_data_processing,Genome_build,Supplementary_files_format_and_content,Sample_data_processing,Sample_data_processing,BioSample,Sample_relation,ID_REF
T1,GSM2155558,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155558
T2,GSM2155559,May 17 2016,Mar 12 2018,breast tumor,0,0,0,1,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155559
T3,GSM2155560,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155560
T4,GSM2155561,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155561
T5,GSM2155562,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
T401,GSM2155958,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155958
T402,GSM2155959,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155959
T403,GSM2155960,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155960
T404,GSM2155961,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155961
T405,GSM2155962,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155962

In [46]:
expression_df.columns

Index(['Sample_geo_accession', 'Sample_submission_date',
       'Sample_last_update_date', 'tissue',
       'er ihc routinestain clinical reading', 'er ihc routinestain reading 2',
       'er ihc routinestain reading 3', 'er ihc restain reading 1',
       'er ihc restain reading 2', 'er ihc restain reading 3', 'er consensus',
       'pgr ihc routinestain clinical reading', 'pgr routinestain reading 2',
       'pgr routinestain reading 3', 'pgr restain reading 1',
       'pgr restain reading 2', 'pgr restain reading 3', 'pgr consensus',
       'her2 ihc clinreading', 'her2 ihc reading 2', 'her2 ihc reading 3',
       'her2 clinical status', 'her2 sish reading 1', 'her2 sish reading 2',
       'her2 sish reading 3', 'her2 consensus', 'ki67 reading 1',
       'ki67 reading 2', 'ki67 reading 3', 'ki67 consensus',
       'nhg reading 1 tubular', 'nhg reading 1 pleomorph',
       'nhg reading 1 mitotic', 'nhg reading 2 tubular',
       'nhg reading 2 pleomorph', 'nhg reading 2 mitotic',
       'nhg reading 3 tubular', 'nhg reading 3 pleomorph',
       'nhg reading 3 mitotic', 'nhg consensus', 'pam50 subtype',
       'Sample_extract_protocol_ch1', 'Sample_description',
       'Sample_description', 'Sample_description', 'Sample_description',
       'Sample_data_processing', 'Sample_data_processing',
       'Sample_data_processing', 'Sample_data_processing',
       'Sample_data_processing', 'Genome_build',
       'Supplementary_files_format_and_content', 'Sample_data_processing',
       'Sample_data_processing', 'BioSample', 'Sample_relation', 'ID_REF'],
      dtype='object')

In [33]:
expression_df = expression_df.loc[:, (expression_df != expression_df.iloc[0]).any()]
expression_df.head()

,Sample_geo_accession,Sample_submission_date,Sample_last_update_date,tissue,er ihc routinestain clinical reading,er ihc routinestain reading 2,er ihc routinestain reading 3,er ihc restain reading 1,er ihc restain reading 2,er ihc restain reading 3,...,Sample_data_processing,Sample_data_processing,Sample_data_processing,Genome_build,Supplementary_files_format_and_content,Sample_data_processing,Sample_data_processing,BioSample,Sample_relation,ID_REF
T1,GSM2155558,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155558
T2,GSM2155559,May 17 2016,Mar 12 2018,breast tumor,0,0,0,1,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155559
T3,GSM2155560,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155560
T4,GSM2155561,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155561
T5,GSM2155562,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155562

In [47]:

expression_df.to_csv(f"Data/{name}.csv", index=True)  # Save as CSV

expression_df

,Sample_geo_accession,Sample_submission_date,Sample_last_update_date,tissue,er ihc routinestain clinical reading,er ihc routinestain reading 2,er ihc routinestain reading 3,er ihc restain reading 1,er ihc restain reading 2,er ihc restain reading 3,...,Sample_data_processing,Sample_data_processing,Sample_data_processing,Genome_build,Supplementary_files_format_and_content,Sample_data_processing,Sample_data_processing,BioSample,Sample_relation,ID_REF
T1,GSM2155558,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155558
T2,GSM2155559,May 17 2016,Mar 12 2018,breast tumor,0,0,0,1,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155559
T3,GSM2155560,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155560
T4,GSM2155561,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155561
T5,GSM2155562,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F2912repl,GSM2531475,Mar 09 2017,Mar 12 2018,Q006763.C006741.S002377.l.r.m.c.lib.g.k.a.t,HiSeq 2000,75,19,1to3,NodePositive,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531475
F2958repl,GSM2531477,Mar 09 2017,Mar 12 2018,Q005521.C005590.S003572.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,33,12,NA,NA,NA,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531477
F3057repl,GSM2531481,Mar 09 2017,Mar 12 2018,Q005327.C005381.S003761.l2.r.m.c.lib.g.k.a.t,HiSeq 2000,76,91,NodeNegative,NodeNegative,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531481
F3085repl,GSM2531483,Mar 09 2017,Mar 12 2018,Q005150.C005183.S003987.l.r.m.c.lib.g.k.a.t,HiSeq 2000,79,10,1to3,NodePositive,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531483
F3135repl,GSM2531485,Mar 09 2017,Mar 12 2018,Q004419.C004480.S004739.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,75,18,NodeNegative,NodeNegative,0,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531485

In [48]:
expression_df

,Sample_geo_accession,Sample_submission_date,Sample_last_update_date,tissue,er ihc routinestain clinical reading,er ihc routinestain reading 2,er ihc routinestain reading 3,er ihc restain reading 1,er ihc restain reading 2,er ihc restain reading 3,...,Sample_data_processing,Sample_data_processing,Sample_data_processing,Genome_build,Supplementary_files_format_and_content,Sample_data_processing,Sample_data_processing,BioSample,Sample_relation,ID_REF
T1,GSM2155558,May 17 2016,Mar 12 2018,breast tumor,0,0,0,0,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155558
T2,GSM2155559,May 17 2016,Mar 12 2018,breast tumor,0,0,0,1,0,0,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155559
T3,GSM2155560,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155560
T4,GSM2155561,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155561
T5,GSM2155562,May 17 2016,Mar 12 2018,breast tumor,3,3,3,3,3,3,...,Remaining reads are aligned using TopHat2 2.0....,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Human genome reference GRCh37/hg19 (with b37 m...,FPKM gene expression in CSV format.,nan,nan,https://www.ncbi.nlm.nih.gov/biosample/SAMN050...,nan,GSM2155562
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F2912repl,GSM2531475,Mar 09 2017,Mar 12 2018,Q006763.C006741.S002377.l.r.m.c.lib.g.k.a.t,HiSeq 2000,75,19,1to3,NodePositive,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531475
F2958repl,GSM2531477,Mar 09 2017,Mar 12 2018,Q005521.C005590.S003572.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,33,12,NA,NA,NA,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531477
F3057repl,GSM2531481,Mar 09 2017,Mar 12 2018,Q005327.C005381.S003761.l2.r.m.c.lib.g.k.a.t,HiSeq 2000,76,91,NodeNegative,NodeNegative,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531481
F3085repl,GSM2531483,Mar 09 2017,Mar 12 2018,Q005150.C005183.S003987.l.r.m.c.lib.g.k.a.t,HiSeq 2000,79,10,1to3,NodePositive,1,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531483
F3135repl,GSM2531485,Mar 09 2017,Mar 12 2018,Q004419.C004480.S004739.l.r.m2.c.lib.g.k.a.t,HiSeq 2000,75,18,NodeNegative,NodeNegative,0,...,Fragment size distribution (mean and width) fo...,Remaining reads were aligned using TopHat2 2.0...,Gene expression data in FPKM were generated us...,PAM50 subtyping was performed using an impleme...,Single-gene classifiers (SGCs) and multi-gene ...,Genome_build: Human genome reference GRCh38/hg38.,Supplementary_files_format_and_content: Gene e...,https://www.ncbi.nlm.nih.gov/biosample/SAMN065...,nan,GSM2531485

In [52]:
expression_df.columns.to_list()[-20:-15]

['nhg reading 3 mitotic',
 'nhg consensus',
 'pam50 subtype',
 'Sample_extract_protocol_ch1',
 'Sample_description']

In [25]:
show_columns= [ 'age at diagnosis',
 'tumor size',
 'lymph node group',
 'lymph node status',
 'er status',
 'pgr status',
 'her2 status',
 'ki67 status',
 'nhg',
 'pam50 subtype',
 'overall survival days',
 'overall survival event',
 'endocrine treated',
 'chemo treated']

In [53]:
len(show_columns)

14

In [26]:
expression_df[show_columns]

,age at diagnosis,tumor size,lymph node group,lymph node status,er status,pgr status,her2 status,ki67 status,nhg,pam50 subtype,overall survival days,overall survival event,endocrine treated,chemo treated
F7,58,18,NodeNegative,NodeNegative,1,NA,0,NA,G2,Normal,2410,0,1,0
F8,56,24,1to3,NodePositive,1,1,0,NA,G2,Normal,2388,0,1,1
F142,46,2,NodeNegative,NodeNegative,NA,NA,NA,NA,G3,Basal,1893,0,0,0
F185,45,13,NodeNegative,NodeNegative,1,1,0,NA,G2,LumA,1950,0,1,0
F219,81,17,NodeNegative,NodeNegative,1,1,0,NA,G2,LumA,1881,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
F3028repl,33,20,1to3,NodePositive,1,1,1,1,G2,LumA,1251,0,1,1
F3058repl,85,23,4toX,NodePositive,1,1,0,1,G2,LumB,1473,0,1,0
F3127repl,69,24,NodeNegative,NodeNegative,1,1,1,1,G3,Her2,1277,0,1,1
F3250repl,42,15,NodeNegative,NodeNegative,0,0,1,1,G3,Her2,904,0,0,1
F3265repl,77,12,NodeNegative,NodeNegative,1,1,0,1,G2,LumA,881,0,0,0

In [ ]:
expression_df['treatment'] = expression_df['endocrine treated'] + expression_df['chemo treated']